### ISSUE TITLE
Can't merge attribute arrays, only override wholesale

### ISSUE THREAD

**Issue by kierenevans** [my127/workspace#64]
This leads to a lot of duplication of a harness into a project.

For example if a harness defines:
```yaml
example:
  foo:
    - one
    - two
    - three
```
but we want to insert "one point five" between "one" and "two", we have to clone the whole array to the project:

```yaml
example:
  foo:
    - one
    - one point five
    - two
    - three
```

This also affects removing something from the array. For example if we don't want two to happen:
```yaml
example:
  foo:
    - one
    - ~
```

Ideally we'd be able to delete/insert as needed without replication, though this may become brittle for harness version upgrades if the array entry values were to change.
