### ISSUE TITLE
Make it easier to use a "master" harness version

### ISSUE THREAD

**Issue by jameshalsall** [my127/workspace#70]
It would be nice if we could have a way of specifying a master harness version directly in the `workspace.yml` without needing to create a `harnesses.json`.

Old way:

`workspace.yml`:
```yaml
workspace('my-app'):
  description: My application
  harness: inviqa/go:v0.7.0
  overlay: tools/workspace

harness.repository.source('local'): ./tools/harnesses.json
```

`tools/harnesses.json`:
```json
{
  "inviqa/go": {
     "v0.7.0": {
      "type": "tar.gz",
      "url": "https://github.com/inviqa/harness-go/archive/master.tar.gz"
     }
  }
}
```

A simplified way could be something like 

`workspace.yml`:
```yaml
workspace('my-app'):
  description: My application
  harness: inviqa/go:master
  overlay: tools/workspace
```

I appreciate this would mean that workspace itself would need to parse the `master` tag, and have awareness of the GitHub archive URLs, and this may not be acceptable.
