### ISSUE TITLE
Support for project harness repo that can overlay the harness a project uses

### ISSUE THREAD

**Issue by andytson-inviqa** [my127/workspace#71]
So that when a project uses many application repos with common files and .my127 overrides in

e.g.

```
workspace('my-app'):
  description: My application
  harnessLayers:
    - inviqa/go:v0.7.0
    - https://git.example.com/mycompany/go/archive/main.tgz
  overlay: tools/workspace
```
